# Generated by Django 5.2.7 on 2026-01-21 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0006_appointment_payment_method"),
    ]

    operations = [
        migrations.CreateModel(
            name="MKB10Diagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Например: M05.8, I10, J45.9",
                        max_length=10,
                        unique=True,
                        verbose_name="Код МКБ-10",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Полное наименование диагноза",
                        max_length=500,
                        verbose_name="Название диагноза",
                    ),
                ),
                (
                    "chapter",
                    models.CharField(
                        blank=True,
                        help_text="Название главы МКБ-10",
                        max_length=100,
                        verbose_name="Глава",
                    ),
                ),
                (
                    "block",
                    models.CharField(
                        blank=True,
                        help_text="Название блока",
                        max_length=200,
                        verbose_name="Блок",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активный диагноз"),
                ),
            ],
            options={
                "verbose_name": "Диагноз МКБ-10",
                "verbose_name_plural": "Диагнозы МКБ-10",
                "ordering": ["code"],
                "indexes": [
                    models.Index(fields=["code"], name="treatment_m_code_0b8f8b_idx"),
                    models.Index(fields=["name"], name="treatment_m_name_e9d145_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DoctorAppointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "complaints",
                    models.TextField(
                        blank=True,
                        help_text="Основные жалобы пациента",
                        verbose_name="Жалобы",
                    ),
                ),
                (
                    "life_anamnesis",
                    models.TextField(
                        blank=True,
                        help_text="Общие сведения о жизни пациента",
                        verbose_name="Анамнез жизни",
                    ),
                ),
                (
                    "disease_anamnesis",
                    models.TextField(
                        blank=True,
                        help_text="История развития текущего заболевания",
                        verbose_name="Анамнез заболевания",
                    ),
                ),
                (
                    "objective_status",
                    models.TextField(
                        blank=True,
                        help_text="Результаты общего осмотра",
                        verbose_name="Объективный статус",
                    ),
                ),
                (
                    "diagnosis",
                    models.TextField(
                        blank=True,
                        help_text="Клинический диагноз",
                        verbose_name="Диагноз",
                    ),
                ),
                (
                    "recommendations",
                    models.TextField(
                        blank=True,
                        help_text="Назначения и рекомендации врача",
                        verbose_name="Рекомендации",
                    ),
                ),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_appointment",
                        to="appointments.appointment",
                        verbose_name="Запись на прием",
                    ),
                ),
                (
                    "mkb10_diagnoses",
                    models.ManyToManyField(
                        blank=True,
                        related_name="appointments",
                        to="treatment.mkb10diagnosis",
                        verbose_name="Диагнозы по МКБ-10",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прием врача",
                "verbose_name_plural": "Приемы врачей",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("appointment",), name="unique_appointment_doctor_exam"
                    )
                ],
            },
        ),
    ]
