# Generated by Django 5.2.7 on 2026-01-21 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0006_appointment_payment_method"),
        ("treatment", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DoctorAppointment",
            new_name="DoctorTreatment",
        ),
    ]
