# Generated by Django 5.2.7 on 2026-01-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("treatment", "0002_rename_doctorappointment_doctortreatment"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctortreatment",
            name="additional_surveys",
            field=models.TextField(
                blank=True,
                help_text="Дополнительные обследования",
                verbose_name="Дополнительные обследования",
            ),
        ),
        migrations.AlterField(
            model_name="doctortreatment",
            name="diagnosis",
            field=models.CharField(
                blank=True,
                help_text="Клинический диагноз",
                max_length=200,
                verbose_name="Диагноз",
            ),
        ),
    ]
