# Generated by Django 5.2.7 on 2026-01-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("treatment", "0003_doctortreatment_additional_surveys_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctortreatment",
            name="diagnosis",
            field=models.CharField(
                blank=True,
                help_text="Клинический диагноз",
                max_length=500,
                verbose_name="Диагноз",
            ),
        ),
    ]
