# Generated by Django 5.2.7 on 2026-01-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("treatment", "0004_alter_doctortreatment_diagnosis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctortreatment",
            name="diagnosis",
            field=models.TextField(
                blank=True, help_text="Клинический диагноз", verbose_name="Диагноз"
            ),
        ),
    ]
