# Generated by Django 5.2.7 on 2025-12-04 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        ("timetable", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Запланирован"),
                            ("confirmed", "Подтвержден"),
                            ("completed", "Завершен"),
                            ("cancelled", "Отменен пациентом"),
                            ("no_show", "Не явился"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="Статус записи",
                    ),
                ),
                (
                    "insurance_type",
                    models.CharField(
                        choices=[("oms", "ОМС"), ("dms", "ДМС"), ("paid", "Платный")],
                        max_length=10,
                        verbose_name="Тип оплаты",
                    ),
                ),
                (
                    "needs_reschedule",
                    models.BooleanField(
                        default=False,
                        verbose_name="Требуется перезапись на более ранний срок",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, verbose_name="Комментарий администратора"
                    ),
                ),
                (
                    "is_consecutive",
                    models.BooleanField(
                        default=False,
                        verbose_name="Запись подряд (второе и последующее 'окно')",
                    ),
                ),
                (
                    "occupies_two_slots",
                    models.BooleanField(
                        default=False,
                        help_text="Отметьте, если услуга требует два последовательных временных слота",
                        verbose_name="Занимает два временных слота",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient",
                        verbose_name="Пациент",
                    ),
                ),
                (
                    "previous_appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appointments.appointment",
                        verbose_name="Предыдущая запись в цепочке",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="timetable.medicalservice",
                        verbose_name="Услуга",
                    ),
                ),
                (
                    "time_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="timetable.timeslot",
                        verbose_name="Временной слот",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись на прием",
                "verbose_name_plural": "Записи на прием",
                "ordering": ["time_slot__date", "time_slot__start_time"],
            },
        ),
        migrations.CreateModel(
            name="AppointmentBloodTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selected_blood_tests",
                        to="appointments.appointment",
                        verbose_name="Запись на прием",
                    ),
                ),
                (
                    "blood_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timetable.bloodtest",
                        verbose_name="Анализ крови",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выбранный анализ крови",
                "verbose_name_plural": "Выбранные анализы крови",
                "unique_together": {("appointment", "blood_test")},
            },
        ),
    ]
