# Generated by Django 5.2.7 on 2025-12-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="price_at_appointment",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Цена услуги на момент создания записи",
                max_digits=10,
                null=True,
                verbose_name="Цена на момент записи",
            ),
        ),
    ]
