# Generated by Django 5.2.7 on 2025-12-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_appointment_price_at_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="total_with_blood_tests",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Общая сумма с анализами",
            ),
        ),
    ]
