# Generated by Django 5.2.7 on 2025-12-16 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_appointment_total_with_blood_tests"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="chain_type",
            field=models.CharField(
                choices=[
                    ("single", "Одиночная запись"),
                    ("same_doctor", "Несколько услуг у одного врача"),
                    ("multiple_doctors", "Записи к разным врачам"),
                    ("procedural", "С процедурным кабинетом"),
                ],
                default="single",
                max_length=20,
                verbose_name="Тип цепочки записей",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="is_chain_main",
            field=models.BooleanField(
                default=False,
                help_text="Отметьте, если это основная запись в цепочке к разным врачам",
                verbose_name="Основная запись в цепочке",
            ),
        ),
        migrations.CreateModel(
            name="AppointmentChain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок в цепочке"
                    ),
                ),
                (
                    "chain_type",
                    models.CharField(
                        choices=[
                            ("same_doctor_additional", "Вторая услуга у того же врача"),
                            ("same_doc_two_slots", "Два слота у того же врача"),
                            ("another_doctor", "Запись к другому врачу"),
                            ("procedural", "Процедурный кабинет"),
                        ],
                        max_length=30,
                        verbose_name="Тип связи",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания связи"
                    ),
                ),
                (
                    "main_appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chain_as_main",
                        to="appointments.appointment",
                        verbose_name="Основная запись",
                    ),
                ),
                (
                    "related_appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chain_as_related",
                        to="appointments.appointment",
                        verbose_name="Связанная запись",
                    ),
                ),
            ],
            options={
                "verbose_name": "Связь записей",
                "verbose_name_plural": "Связи записей",
                "ordering": ["order"],
                "unique_together": {("main_appointment", "related_appointment")},
            },
        ),
    ]
