# Generated by Django 5.2.7 on 2025-12-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0004_add_appointment_chain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentchain",
            name="chain_type",
            field=models.CharField(
                choices=[
                    ("same_doctor_additional", "Вторая услуга у того же врача"),
                    ("same_doc_two_slots", "Два слота у того же врача"),
                    ("another_doctor", "Запись к другому врачу"),
                    ("procedural", "Процедурный кабинет"),
                ],
                default="another_doctor",
                max_length=30,
                verbose_name="Тип связи",
            ),
        ),
    ]
