# Generated by Django 5.2.7 on 2026-01-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0005_fix_appointment_chain_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Наличные"),
                    ("card", "Карта"),
                    ("none", "Не выбрано"),
                ],
                default="none",
                max_length=20,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
