# Generated by Django 5.2.7 on 2025-12-04 09:55

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BloodTestCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название категории"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Активная категория"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория анализов крови",
                "verbose_name_plural": "Категории анализов крови",
            },
        ),
        migrations.CreateModel(
            name="Cabinet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="Номер кабинета"
                    ),
                ),
                (
                    "name_of_cabinet",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Название/описание кабинета",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кабинет",
                "verbose_name_plural": "Кабинеты",
            },
        ),
        migrations.CreateModel(
            name="DayComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Дата")),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Комментарий дня",
                "verbose_name_plural": "Комментарии дней",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="MedicalService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, verbose_name="Код услуги")),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название услуги"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена услуги"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("joint_us", "УЗИ суставов"),
                            ("organ_us", "УЗИ внутренних органов"),
                            ("doppler", "Ультразвуковая допплерография"),
                            ("densitometry", "Ультразвуковая денситометрия"),
                            ("xray", "Рентген"),
                            ("first_consult", "Первичная консультация"),
                            ("second_consult", "Повторная консультация"),
                            ("manufacture_of_insoles", "Изготовление стелек"),
                            ("analyzes", "Анализы"),
                            ("medical_blockades", "Медикаментозные блокады"),
                            ("physio_procedures", "Физио процедуры"),
                        ],
                        max_length=30,
                        verbose_name="Категория услуги",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание услуги"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активная услуга"),
                ),
            ],
            options={
                "verbose_name": "Медицинская услуга",
                "verbose_name_plural": "Медицинские услуги",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="BloodTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=25, verbose_name="Код услуги")),
                (
                    "name",
                    models.CharField(
                        max_length=500, unique=True, verbose_name="Наименование анализа"
                    ),
                ),
                (
                    "biomaterial",
                    models.CharField(
                        choices=[
                            ("serum", "Кровь (сыворотка)"),
                            ("plasma", "Кровь (плазма с NaCi)"),
                            ("edta", "Кровь (ЭДТА)"),
                            ("lithium_heparin", "Кровь (литий-гепарин)"),
                        ],
                        default="serum",
                        max_length=20,
                        verbose_name="Биоматериал",
                    ),
                ),
                (
                    "execution_time",
                    models.CharField(
                        default="1 день", max_length=50, verbose_name="Срок выполнения"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tests",
                        to="timetable.bloodtestcategory",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Анализ крови",
                "verbose_name_plural": "Анализы крови",
            },
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=20, verbose_name="Имя врача"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=30, verbose_name="Отчество врача"),
                ),
                (
                    "surname",
                    models.CharField(max_length=50, verbose_name="Фамилия врача"),
                ),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("rheumatologist", "Ревматолог"),
                            ("Orthopedic-traumatologist", "Травматолог-ортопед"),
                            ("nurse", "Медсестра"),
                            ("neurologist", "Невролог"),
                            ("cardiologist", "Кардиолог"),
                            ("gastroenterologist", "Гастроэнтеролог"),
                            ("nephrologist", "Нефролог"),
                            ("dermatovenerologist", "Дерматовенеролог"),
                            (
                                "ultrasound_diagnostics_doctor",
                                "Врач ультразвуковой диагностики",
                            ),
                            ("radiologist", "Рентгенолаборант"),
                        ],
                        max_length=50,
                        verbose_name="Основная специализация",
                    ),
                ),
                (
                    "provided_services",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("joint_us", "УЗИ суставов"),
                            ("organ_us", "УЗИ внутренних органов"),
                            ("doppler", "Ультразвуковая допплерография"),
                            ("densitometry", "Ультразвуковая денситометрия"),
                            ("xray", "Рентген"),
                            ("first_consult", "Первичная консультация"),
                            ("second_consult", "Повторная консультация"),
                            ("manufacture_of_insoles", "Изготовление стелек"),
                            ("analyzes", "Анализы"),
                            ("medical_blockades", "Медикаментозные блокады"),
                            ("physio_procedures", "Физио процедуры"),
                        ],
                        help_text="Выберите категории услуг, которые оказывает врач",
                        max_length=200,
                        verbose_name="Категории оказываемых услуг",
                    ),
                ),
                (
                    "schedule_comment",
                    models.TextField(
                        blank=True,
                        help_text="Этот комментарий будет отображаться перед слотами врача в расписании",
                        verbose_name="Комментарий для расписания",
                    ),
                ),
                (
                    "excluded_services",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Услуги, которые недоступны для этого врача (исключения из категорий)",
                        to="timetable.medicalservice",
                        verbose_name="Исключенные услуги",
                    ),
                ),
            ],
            options={
                "verbose_name": "Врач",
                "verbose_name_plural": "Врачи",
            },
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата расписания")),
                ("start_time", models.TimeField(verbose_name="Время начала")),
                ("end_time", models.TimeField(verbose_name="Время окончания")),
                (
                    "slot_type",
                    models.CharField(
                        choices=[("working", "Рабочий слот"), ("break", "Перерыв")],
                        default="working",
                        max_length=10,
                        verbose_name="Тип слота",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Описание"
                    ),
                ),
                (
                    "cabinet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timetable.cabinet",
                        verbose_name="Кабинет",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timetable.doctor",
                        verbose_name="Врач",
                    ),
                ),
            ],
            options={
                "verbose_name": "Слот расписания",
                "verbose_name_plural": "Слоты расписания",
                "ordering": ["date", "cabinet", "start_time"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("doctor", "date", "start_time"),
                        name="unique_doctor_time_slot",
                    )
                ],
            },
        ),
    ]
