# Generated by Django 5.2.7 on 2025-10-05 19:11

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cabinet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="Номер кабинета"
                    ),
                ),
                (
                    "name_of_cabinet",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Название/описание кабинета",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кабинет",
                "verbose_name_plural": "Кабинеты",
            },
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=20, verbose_name="Имя врача"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=30, verbose_name="Отчество врача"),
                ),
                (
                    "surname",
                    models.CharField(max_length=50, verbose_name="Фамилия врача"),
                ),
                (
                    "specialization",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("rheumatologist_1", "Ревматолог категория 1"),
                            ("rheumatologist_2", "Ревматолог категория 2"),
                            ("rheumatologist_3", "Ревматолог категория 3"),
                            ("Orthopedic-traumatologist", "Травматолог-ортопед"),
                            ("nurse", "Медсестра"),
                            ("neurologist", "Невролог"),
                            ("cardiologist", "Кардиолог"),
                            ("gastroenterologist", "Гастроэнтеролог"),
                            ("nephrologist", "Нефролог"),
                            ("dermatovenerologist", "Дерматовенеролог"),
                            (
                                "ultrasound_diagnostics_doctor",
                                "Врач ультразвуковой диагностики",
                            ),
                            ("radiologist", "Рентгенолог"),
                        ],
                        help_text="Выберите специализации врача",
                        max_length=200,
                        verbose_name="Специализации врача",
                    ),
                ),
                (
                    "provided_services",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("joint_us", "УЗИ суставов"),
                            ("organ_us", "УЗИ внутренних органов"),
                            ("doppler", "Ультразвуковая допплерография"),
                            ("densitometry", "Ультразвуковая денситометрия"),
                            ("xray", "Рентген"),
                            ("first_consult", "Первичная консультация"),
                            ("second_consult", "Повторная консультация"),
                            ("manufacture_of_insoles", "Изготовление стелек"),
                            ("analyzes", "Анализы"),
                            ("medical_blockades", "Медикаментозные блокады"),
                        ],
                        help_text="Выберите категории услуг, которые оказывает врач",
                        max_length=200,
                        verbose_name="Оказываемые категории услуг",
                    ),
                ),
            ],
            options={
                "verbose_name": "Врач",
                "verbose_name_plural": "Врачи",
            },
        ),
        migrations.CreateModel(
            name="MedicalService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название услуги"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Код услуги"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена услуги"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("joint_us", "УЗИ суставов"),
                            ("organ_us", "УЗИ внутренних органов"),
                            ("doppler", "Ультразвуковая допплерография"),
                            ("densitometry", "Ультразвуковая денситометрия"),
                            ("xray", "Рентген"),
                            ("first_consult", "Первичная консультация"),
                            ("second_consult", "Повторная консультация"),
                            ("manufacture_of_insoles", "Изготовление стелек"),
                            ("analyzes", "Анализы"),
                            ("medical_blockades", "Медикаментозные блокады"),
                        ],
                        max_length=30,
                        verbose_name="Категория услуги",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание услуги"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активная услуга"),
                ),
                (
                    "allowed_specializations",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("rheumatologist_1", "Ревматолог категория 1"),
                            ("rheumatologist_2", "Ревматолог категория 2"),
                            ("rheumatologist_3", "Ревматолог категория 3"),
                            ("Orthopedic-traumatologist", "Травматолог-ортопед"),
                            ("nurse", "Медсестра"),
                            ("neurologist", "Невролог"),
                            ("cardiologist", "Кардиолог"),
                            ("gastroenterologist", "Гастроэнтеролог"),
                            ("nephrologist", "Нефролог"),
                            ("dermatovenerologist", "Дерматовенеролог"),
                            (
                                "ultrasound_diagnostics_doctor",
                                "Врач ультразвуковой диагностики",
                            ),
                            ("radiologist", "Рентгенолог"),
                        ],
                        max_length=500,
                        verbose_name="Разрешенные специализации",
                    ),
                ),
            ],
            options={
                "verbose_name": "Медицинская услуга",
                "verbose_name_plural": "Медицинские услуги",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=20, verbose_name="Имя пациента"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=30, verbose_name="Отчество пациента"),
                ),
                (
                    "surname",
                    models.CharField(max_length=50, verbose_name="Фамилия пациента"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=12, verbose_name="Телефон пациента"),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата рождения пациента"
                    ),
                ),
                (
                    "registration_address",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Адрес регистрации пациента",
                    ),
                ),
                (
                    "residential_address",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Адрес проживания пациента",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пациент",
                "verbose_name_plural": "Пациенты",
            },
        ),
    ]
