# Generated by Django 5.2.7 on 2025-10-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="schedule_comment",
            field=models.TextField(
                blank=True,
                help_text="Этот комментарий будет отображаться перед слотами врача в расписании",
                verbose_name="Комментарий для расписания",
            ),
        ),
    ]
