# Generated by Django 5.2.7 on 2025-10-06 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата расписания")),
                ("start_time", models.TimeField(verbose_name="Время начала")),
                ("end_time", models.TimeField(verbose_name="Время окончания")),
                (
                    "slot_type",
                    models.CharField(
                        choices=[("working", "Рабочий слот"), ("break", "Перерыв")],
                        default="working",
                        max_length=10,
                        verbose_name="Тип слота",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Описание"
                    ),
                ),
                (
                    "cabinet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timetable.cabinet",
                        verbose_name="Кабинет",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timetable.doctor",
                        verbose_name="Врач",
                    ),
                ),
            ],
            options={
                "verbose_name": "Слот расписания",
                "verbose_name_plural": "Слоты расписания",
                "ordering": ["date", "cabinet", "start_time"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("doctor", "date", "start_time"),
                        name="unique_doctor_time_slot",
                    )
                ],
            },
        ),
    ]
