# Generated by Django 5.2.7 on 2025-12-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="specialization",
            field=models.CharField(
                choices=[
                    ("rheumatologist", "Ревматолог"),
                    ("Orthopedic-traumatologist", "Травматолог-ортопед"),
                    ("nurse", "Медсестра"),
                    ("neurologist", "Невролог"),
                    ("cardiologist", "Кардиолог"),
                    ("gastroenterologist", "Гастроэнтеролог"),
                    ("nephrologist", "Нефролог"),
                    ("dermatovenerologist", "Дерматовенеролог"),
                    (
                        "specialist_in_psychological_support)",
                        "Специалист по психологическому сопровождению",
                    ),
                    (
                        "ultrasound_diagnostics_doctor",
                        "Врач ультразвуковой диагностики",
                    ),
                    ("radiologist", "Рентгенолаборант"),
                ],
                max_length=50,
                verbose_name="Основная специализация",
            ),
        ),
    ]
