# Generated by Django 5.2.7 on 2025-10-05 12:25

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doctor",
            options={"verbose_name": "Врач", "verbose_name_plural": "Врачи"},
        ),
        migrations.AlterModelOptions(
            name="patient",
            options={"verbose_name": "Пациент", "verbose_name_plural": "Пациенты"},
        ),
        migrations.AddField(
            model_name="medicalservice",
            name="allowed_specializations",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("rheumatologist_1", "Ревматолог категория 1"),
                    ("rheumatologist_2", "Ревматолог категория 2"),
                    ("rheumatologist_3", "Ревматолог категория 3"),
                    ("Orthopedic-traumatologist", "Травматолог-ортопед"),
                    ("neurologist", "Невролог"),
                    ("cardiologist", "Кардиолог"),
                    ("gastroenterologist", "Гастроэнтеролог"),
                    ("nephrologist", "Нефролог"),
                    ("dermatovenerologist", "Дерматовенеролог"),
                ],
                max_length=500,
                verbose_name="Разрешенные специализации",
            ),
        ),
    ]
