# Generated by Django 5.2.7 on 2025-10-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0002_doctor_schedule_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="occupies_two_slots",
            field=models.BooleanField(
                default=False,
                help_text="Отметьте, если услуга требует два последовательных временных слота",
                verbose_name="Занимает два временных слота",
            ),
        ),
    ]
