# Generated by Django 5.2.7 on 2025-10-06 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0002_timeslot"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата приема")),
                ("start_time", models.TimeField(verbose_name="Время начала")),
                ("end_time", models.TimeField(verbose_name="Время окончания")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Запланирован"),
                            ("confirmed", "Подтвержден"),
                            ("completed", "Завершен"),
                            ("cancelled", "Отменен пациентом"),
                            ("no_show", "Не явился"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="Статус записи",
                    ),
                ),
                (
                    "insurance_type",
                    models.CharField(
                        choices=[("oms", "ОМС"), ("dms", "ДМС"), ("paid", "Платный")],
                        max_length=10,
                        verbose_name="Тип оплаты",
                    ),
                ),
                (
                    "guarantee_letter_received",
                    models.BooleanField(
                        default=False, verbose_name="Гарантийное письмо получено"
                    ),
                ),
                (
                    "needs_reschedule",
                    models.BooleanField(
                        default=False,
                        verbose_name="Требуется перезапись на более ранний срок",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, verbose_name="Комментарий администратора"
                    ),
                ),
                (
                    "is_consecutive",
                    models.BooleanField(
                        default=False,
                        verbose_name="Запись подряд (второе и последующее 'окно')",
                    ),
                ),
                (
                    "cabinet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="timetable.cabinet",
                        verbose_name="Кабинет",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timetable.doctor",
                        verbose_name="Врач",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timetable.patient",
                        verbose_name="Пациент",
                    ),
                ),
                (
                    "previous_appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="timetable.appointment",
                        verbose_name="Предыдущая запись в цепочке",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="timetable.medicalservice",
                        verbose_name="Услуга",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись на прием",
                "verbose_name_plural": "Записи на прием",
                "ordering": ["date", "start_time"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("doctor", "date", "start_time"),
                        name="unique_appointment_doctor_time",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("cabinet__isnull", False)),
                        fields=("cabinet", "date", "start_time"),
                        name="unique_appointment_cabinet_time",
                    ),
                    models.UniqueConstraint(
                        fields=("patient", "date", "start_time"),
                        name="unique_appointment_patient_time",
                    ),
                ],
            },
        ),
    ]
