# Generated by Django 5.2.7 on 2026-01-03 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0002_alter_doctor_specialization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="specialization",
            field=models.CharField(
                choices=[
                    ("rheumatologist", "Ревматолог"),
                    ("Orthopedic-traumatologist", "Травматолог-ортопед"),
                    ("nurse", "Старшая медсестра"),
                    ("neurologist", "Невролог"),
                    ("cardiologist", "Кардиолог"),
                    ("gastroenterologist", "Гастроэнтеролог"),
                    ("nephrologist", "Нефролог"),
                    ("dermatovenerologist", "Дерматовенеролог"),
                    (
                        "specialist_in_psychological_support)",
                        "Специалист по психологическому сопровождению психосоматических расстройств",
                    ),
                    (
                        "ultrasound_diagnostics_doctor",
                        "Врач ультразвуковой диагностики",
                    ),
                    ("radiologist", "Рентгенолаборант"),
                ],
                max_length=50,
                verbose_name="Основная специализация",
            ),
        ),
        migrations.CreateModel(
            name="CabinetDayComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cabinet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="day_comments",
                        to="timetable.cabinet",
                        verbose_name="Кабинет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий кабинета",
                "verbose_name_plural": "Комментарии кабинетов",
                "ordering": ["date", "cabinet__number"],
                "unique_together": {("date", "cabinet")},
            },
        ),
    ]
