# Generated by Django 5.2.7 on 2025-11-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0002_alter_doctor_specialization"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="procedural_type",
            field=models.CharField(
                choices=[
                    ("nurse_required", "Требуется медсестра"),
                    ("nurse_not_required", "Медсестра не требуется"),
                ],
                default="nurse_not_required",
                help_text="Определяет, нужно ли привязывать запись к медсестре",
                max_length=20,
                verbose_name="Тип процедурной записи",
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="specialization",
            field=models.CharField(
                choices=[
                    ("rheumatologist", "Ревматолог"),
                    ("Orthopedic-traumatologist", "Травматолог-ортопед"),
                    ("nurse", "Медсестра"),
                    ("neurologist", "Невролог"),
                    ("cardiologist", "Кардиолог"),
                    ("gastroenterologist", "Гастроэнтеролог"),
                    ("nephrologist", "Нефролог"),
                    ("dermatovenerologist", "Дерматовенеролог"),
                    (
                        "ultrasound_diagnostics_doctor",
                        "Врач ультразвуковой диагностики",
                    ),
                    ("radiologist", "Рентгенолог"),
                ],
                max_length=50,
                verbose_name="Основная специализация",
            ),
        ),
    ]
