# Generated by Django 5.2.7 on 2025-10-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0003_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="card_number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Номер карты пациента"
            ),
        ),
    ]
