# Generated by Django 5.2.7 on 2025-10-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0003_appointment_occupies_two_slots"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="patient",
            constraint=models.UniqueConstraint(
                fields=("surname", "first_name", "last_name", "date_of_birth"),
                name="unique_patient_full_info",
            ),
        ),
    ]
