# Generated by Django 5.2.7 on 2025-11-28 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0003_appointment_procedural_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BloodTestCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название категории"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Активная категория"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория анализов крови",
                "verbose_name_plural": "Категории анализов крови",
            },
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="procedural_type",
        ),
        migrations.CreateModel(
            name="BloodTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, verbose_name="Код услуги")),
                (
                    "name",
                    models.CharField(
                        max_length=500, verbose_name="Наименование анализа"
                    ),
                ),
                (
                    "biomaterial",
                    models.CharField(
                        choices=[
                            ("serum", "Кровь (сыворотка)"),
                            ("plasma", "Кровь (плазма с NaCi)"),
                            ("edta", "Кровь (ЭДТА)"),
                            ("lithium_heparin", "Кровь (литий-гепарин)"),
                        ],
                        default="serum",
                        max_length=20,
                        verbose_name="Биоматериал",
                    ),
                ),
                (
                    "execution_time",
                    models.CharField(
                        default="1 день", max_length=50, verbose_name="Срок выполнения"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tests",
                        to="timetable.bloodtestcategory",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Анализ крови",
                "verbose_name_plural": "Анализы крови",
            },
        ),
    ]
