# Generated by Django 5.2.7 on 2026-02-11 18:51

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0003_alter_doctor_specialization_cabinetdaycomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="provided_services",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("joint_us", "УЗИ суставов"),
                    ("organ_us", "УЗИ внутренних органов"),
                    ("doppler", "Ультразвуковая допплерография"),
                    ("densitometry", "Ультразвуковая денситометрия"),
                    ("xray", "Рентген"),
                    ("first_consult", "Первичная консультация"),
                    ("second_consult", "Повторная консультация"),
                    ("manufacture_of_insoles", "Плантография"),
                    ("analyzes", "Анализы"),
                    ("medical_blockades", "Медикаментозные блокады"),
                    ("physio_procedures", "Физио процедуры"),
                ],
                help_text="Выберите категории услуг, которые оказывает врач",
                max_length=200,
                verbose_name="Категории оказываемых услуг",
            ),
        ),
    ]
