# Generated by Django 5.2.7 on 2025-10-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0004_patient_card_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="Телефон пациента"
            ),
        ),
    ]
