# Generated by Django 5.2.7 on 2025-11-28 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "timetable",
            "0004_bloodtestcategory_remove_appointment_procedural_type_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentBloodTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selected_blood_tests",
                        to="timetable.appointment",
                        verbose_name="Запись на прием",
                    ),
                ),
                (
                    "blood_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timetable.bloodtest",
                        verbose_name="Анализ крови",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выбранный анализ крови",
                "verbose_name_plural": "Выбранные анализы крови",
                "unique_together": {("appointment", "blood_test")},
            },
        ),
    ]
