# Generated by Django 5.2.7 on 2026-02-23 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0004_alter_doctor_provided_services"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalServicePrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valid_from", models.DateField(verbose_name="Действует с")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="timetable.medicalservice",
                        verbose_name="Услуга",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цена услуги",
                "verbose_name_plural": "Цены услуг",
                "ordering": ["-valid_from"],
                "indexes": [
                    models.Index(
                        fields=["service", "valid_from"], name="idx_service_valid_from"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("service", "valid_from"), name="uniq_service_valid_from"
                    )
                ],
            },
        ),
    ]
