# Generated by Django 5.2.7 on 2025-10-11 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0004_patient_unique_patient_full_info"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="registration_address",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="residential_address",
        ),
    ]
