# Generated by Django 5.2.7 on 2025-10-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0005_remove_patient_registration_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalservice",
            name="code",
            field=models.CharField(max_length=20, verbose_name="Код услуги"),
        ),
    ]
