# Generated by Django 5.2.7 on 2025-11-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0005_appointmentbloodtest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloodtest",
            name="code",
            field=models.CharField(max_length=25, verbose_name="Код услуги"),
        ),
        migrations.AlterField(
            model_name="bloodtest",
            name="name",
            field=models.CharField(
                max_length=500, unique=True, verbose_name="Наименование анализа"
            ),
        ),
    ]
