# Generated by Django 5.2.7 on 2025-10-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0006_alter_medicalservice_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="excluded_services",
            field=models.ManyToManyField(
                blank=True,
                help_text="Услуги, которые недоступны для этого врача (исключения из категорий)",
                to="timetable.medicalservice",
                verbose_name="Исключенные услуги",
            ),
        ),
    ]
