# Generated by Django 5.2.7 on 2025-10-21 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0008_alter_patient_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="previous_appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="timetable.appointment",
                verbose_name="Предыдущая запись в цепочке",
            ),
        ),
        migrations.AlterConstraint(
            model_name="patient",
            name="unique_patient_full_info",
            constraint=models.UniqueConstraint(
                fields=("surname", "first_name", "last_name", "date_of_birth"),
                name="unique_patient_full_info",
                violation_error_message="Пациент с такими ФИО и датой рождения уже существует в базе.",
            ),
        ),
    ]
