# Generated by Django 5.2.7 on 2025-10-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0009_alter_appointment_previous_appointment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DayComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Дата")),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Комментарий дня",
                "verbose_name_plural": "Комментарии дней",
                "ordering": ["-date"],
            },
        ),
    ]
