# Generated by Django 5.2.7 on 2025-12-02 15:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=20, verbose_name="Имя пациента"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=30, verbose_name="Отчество пациента"),
                ),
                (
                    "surname",
                    models.CharField(max_length=50, verbose_name="Фамилия пациента"),
                ),
                (
                    "card_number",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Номер карты пациента"
                    ),
                ),
                (
                    "card_number_IP",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Номер карты пациента (ИП)"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=12,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Номер телефона должен начинаться с +7 и содержать 12 символов",
                                regex="^\\+7\\d{10}$",
                            )
                        ],
                        verbose_name="Телефон пациента",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата рождения пациента"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "Мужской"), ("female", "Женский")],
                        max_length=10,
                        null=True,
                        verbose_name="Пол",
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Субъект РФ"
                    ),
                ),
                (
                    "locality",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Населенный пункт",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Город"
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Район"
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Улица"
                    ),
                ),
                (
                    "home",
                    models.CharField(
                        blank=True, max_length=4, null=True, verbose_name="Дом"
                    ),
                ),
                (
                    "building",
                    models.CharField(
                        blank=True,
                        max_length=4,
                        null=True,
                        verbose_name="Строение/корпус",
                    ),
                ),
                (
                    "apartment",
                    models.CharField(
                        blank=True, max_length=5, null=True, verbose_name="Квартира"
                    ),
                ),
                (
                    "passport_series",
                    models.CharField(
                        blank=True,
                        max_length=4,
                        null=True,
                        verbose_name="Паспорт серия",
                    ),
                ),
                (
                    "passport_number",
                    models.CharField(
                        blank=True,
                        max_length=6,
                        null=True,
                        verbose_name="Паспорт номер",
                    ),
                ),
                (
                    "passport_issue_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата выдачи паспорта"
                    ),
                ),
                (
                    "who_issued_the_passport",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Кем выдан паспорт",
                    ),
                ),
                (
                    "polis_oms",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Полис ОМС"
                    ),
                ),
                (
                    "snils",
                    models.CharField(
                        blank=True, max_length=14, null=True, verbose_name="СНИЛС"
                    ),
                ),
                (
                    "insurance_company",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Страховая компания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пациент",
                "verbose_name_plural": "Пациенты",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("surname", "first_name", "last_name", "date_of_birth"),
                        name="unique_patient_full_info_patients",
                        violation_error_message="Пациент с такими ФИО и датой рождения уже существует в базе.",
                    )
                ],
            },
        ),
    ]
