# Generated by Django 5.2.7 on 2025-12-09 19:21

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patient",
            options={
                "ordering": ["surname", "first_name", "last_name"],
                "verbose_name": "Пациент",
                "verbose_name_plural": "Пациенты",
            },
        ),
        migrations.RemoveConstraint(
            model_name="patient",
            name="unique_patient_full_info_patients",
        ),
        migrations.AlterField(
            model_name="patient",
            name="apartment",
            field=models.CharField(
                blank=True, default="", max_length=5, verbose_name="Квартира"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="area",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Субъект РФ"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="building",
            field=models.CharField(
                blank=True, default="", max_length=4, verbose_name="Корпус/строение"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="card_number",
            field=models.PositiveIntegerField(
                blank=True, null=True, unique=True, verbose_name="Номер карты"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="card_number_IP",
            field=models.PositiveIntegerField(
                blank=True, null=True, unique=True, verbose_name="Номер карты (ИП)"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="card_number_OMS",
            field=models.PositiveIntegerField(
                blank=True, null=True, unique=True, verbose_name="Номер карты (ОМС)"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="city",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Город"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="district",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Район"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="first_name",
            field=models.CharField(
                help_text="Обязательное поле", max_length=20, verbose_name="Имя"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Мужской"), ("female", "Женский")],
                default="",
                max_length=10,
                verbose_name="Пол",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="home",
            field=models.CharField(
                blank=True, default="", max_length=4, verbose_name="Дом"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="insurance_company",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="Страховая компания",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="last_name",
            field=models.CharField(
                blank=True, default="", max_length=30, verbose_name="Отчество"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="locality",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Населенный пункт"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="passport_issue_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата выдачи"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="passport_number",
            field=models.CharField(
                blank=True, default="", max_length=6, verbose_name="Номер паспорта"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="passport_series",
            field=models.CharField(
                blank=True, default="", max_length=4, verbose_name="Серия паспорта"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Формат: +7XXXXXXXXXX",
                max_length=128,
                null=True,
                region="RU",
                verbose_name="Телефон",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="polis_oms",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="Полис ОМС"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="snils",
            field=models.CharField(
                blank=True, default="", max_length=14, verbose_name="СНИЛС"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="street",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Улица"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="surname",
            field=models.CharField(
                help_text="Обязательное поле", max_length=50, verbose_name="Фамилия"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="who_issued_the_passport",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Кем выдан"
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["surname", "first_name"], name="patients_pa_surname_6fa89a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["phone_number"], name="patients_pa_phone_n_933975_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["card_number"], name="patients_pa_card_nu_8cca49_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="patient",
            constraint=models.UniqueConstraint(
                fields=("surname", "first_name", "last_name", "date_of_birth"),
                name="unique_patient_full_info",
                violation_error_message="Пациент с такими ФИО и датой рождения уже существует",
            ),
        ),
    ]
