# Generated by Django 5.2.7 on 2025-10-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="passport",
        ),
        migrations.AddField(
            model_name="patient",
            name="passport_number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Паспорт номер"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="passport_series",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Паспорт серия"
            ),
        ),
    ]
