# Generated by Django 5.2.7 on 2025-10-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_remove_patient_passport_patient_passport_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="address",
        ),
        migrations.AddField(
            model_name="patient",
            name="apartment",
            field=models.CharField(
                blank=True, max_length=5, null=True, verbose_name="Квартира"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="building",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="Строение/корпус"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="home",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="Дом"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="street",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Улица"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="passport_number",
            field=models.CharField(
                blank=True, max_length=6, null=True, verbose_name="Паспорт номер"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="passport_series",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="Паспорт серия"
            ),
        ),
    ]
