# Generated by Django 5.2.7 on 2025-12-16 19:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_alter_patient_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=12,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Номер телефона должен начинаться с +7 и содержать 12 символов",
                        regex="^\\+7\\d{10}$",
                    )
                ],
                verbose_name="Телефон пациента",
            ),
        ),
    ]
