# Generated by Django 5.2.7 on 2026-01-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0003_alter_patient_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="card_number_OMS",
            field=models.CharField(
                blank=True, null=True, unique=True, verbose_name="Номер карты (ОМС)"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="home",
            field=models.CharField(
                blank=True, default="", max_length=8, verbose_name="Дом"
            ),
        ),
    ]
