# Generated by Django 5.2.7 on 2025-10-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0003_remove_patient_address_patient_apartment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="card_number_IP",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Номер карты пациента (ИП)"
            ),
        ),
    ]
