# Generated by Django 5.2.7 on 2025-11-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0004_patient_card_number_ip"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="passport_issue_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата выдачи паспорта"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="who_issued_the_passport",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Кем выдан паспорт"
            ),
        ),
    ]
