# Generated by Django 5.2.7 on 2026-01-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0004_alter_patient_card_number_oms_alter_patient_home"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="card_number_OMS",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Номер карты (ОМС)",
            ),
        ),
    ]
