# Generated by Django 5.2.7 on 2026-01-08 12:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0005_alter_patient_card_number_oms"),
        ("timetable", "0003_alter_doctor_specialization_cabinetdaycomment"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReserveList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.PositiveSmallIntegerField(verbose_name="Месяц (1-12)"),
                ),
                ("year", models.PositiveSmallIntegerField(verbose_name="Год")),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timetable.doctor",
                        verbose_name="Врач",
                    ),
                ),
            ],
            options={
                "verbose_name": "Список резерва",
                "verbose_name_plural": "Списки резерва",
                "ordering": ["-year", "-month", "doctor"],
                "unique_together": {("doctor", "month", "year")},
            },
        ),
        migrations.CreateModel(
            name="ReservePatient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surname", models.CharField(max_length=50, verbose_name="Фамилия")),
                ("first_name", models.CharField(max_length=20, verbose_name="Имя")),
                (
                    "last_name",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="Отчество"
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата рождения"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=12,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Номер телефона должен начинаться с +7 и содержать 12 символов",
                                regex="^\\+7\\d{10}$",
                            )
                        ],
                        verbose_name="Телефон пациента",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient",
                        verbose_name="Пациент (если найден в БД)",
                    ),
                ),
                (
                    "reserve_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="patients.reservelist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись резерва",
                "verbose_name_plural": "Записи резерва",
            },
        ),
    ]
