# Generated by Django 5.2.7 on 2026-01-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0006_reservelist_reservepatient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="apartment",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="Квартира"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="building",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="Корпус/строение"
            ),
        ),
    ]
