# Generated by Django 5.2.7 on 2026-01-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0007_alter_patient_apartment_alter_patient_building"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="apartment",
            field=models.CharField(
                blank=True, default="", max_length=5, verbose_name="Квартира"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="building",
            field=models.CharField(
                blank=True, default="", max_length=4, verbose_name="Корпус/строение"
            ),
        ),
    ]
