# Generated by Django 5.2.7 on 2026-01-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0008_alter_patient_apartment_alter_patient_building"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Электронная почта пациента",
                max_length=254,
                null=True,
                verbose_name="Email",
            ),
        ),
    ]
