# Generated by Django 5.2.7 on 2026-02-08 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0009_patient_email"),
        ("timetable", "0003_alter_doctor_specialization_cabinetdaycomment"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaitlistPatient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surname", models.CharField(max_length=50, verbose_name="Фамилия")),
                ("first_name", models.CharField(max_length=20, verbose_name="Имя")),
                (
                    "last_name",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="Отчество"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=12,
                        null=True,
                        verbose_name="Телефон пациента",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата рождения"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Ожидает"),
                            ("contacted", "Связались"),
                            ("scheduled", "Записан"),
                            ("cancelled", "Отменен"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timetable.doctor",
                        verbose_name="Врач",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient",
                        verbose_name="Пациент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пациент листа ожидания",
                "verbose_name_plural": "Пациенты листа ожидания",
                "ordering": ["-created_at"],
            },
        ),
    ]
