# Generated by Django 5.2.7 on 2026-02-08 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0010_waitlistpatient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="waitlistpatient",
            name="status",
        ),
    ]
