# Generated by Django 5.2.7 on 2026-02-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0011_remove_waitlistpatient_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="trusted_person",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Доверенное лицо"
            ),
        ),
    ]
